### ISSUE TITLE
Questions re misp docker image esp. user that runs MISP

### ISSUE THREAD

**Issue by chrisinmtown** [coolacid/docker-misp#111]
I would like to ask a few questions, please, I hope it's ok to write an issue for that.  Here goes:

1. entrypoint_nginx.sh creates a file entrypoint_apache.install, that seems like a name mis-match, is that on purpose?

https://github.com/coolacid/docker-misp/blob/f987fe180ff3d818469cffe1299b96be02f11991/server/files/entrypoint_nginx.sh#L13

2. What user runs the nginx server, MISP server and PHP processes?  From looking at the config here I *think* it might be root running nginx and www-user running MISP, but not certain I got that right.  I'm asking cos we get beaten up to use least privilege and that means not running any processes as root inside any container. Would you please mention this detail in the README.md ?

3. The running docker container must have quite a few processes such as php-fpm, do I have that right? I guess by default the running container can grab as much of the host CPU as it likes, do you recommend any configuration to make sure the running container does not use too many resources?

Thanks in advance for your time.

**Comment by coolacid** [comment]
1. This is a hold over from when it was running apache. I forgot to change it, originally nginx was a proof of concept and I pulled the trigger after a few weeks didn't go back to rename this file. 

2. I'm actually not 100% sure on this. nginx will probably at least start as root since it has to listen on 80/443 (Yes, I know I could make it high port and let docker port map it, but not everyone groks that concept). php-fpm runs as `www-data` hence the chown in the nginx entrypoint. cron runs as root, but the processes that we run drop to `www-data`  Workers also drop to `www-data` on startup. 

3. The docker container runs nginx, php-fpm, workers and cron. There is no way around this. All instances I run are on dedicated VMs, so there is no docker resource constraints. I'd suggest you check with the MISP project for their recommendations on overall resources.

**Comment by chrisinmtown** [comment]
thanks for the answers.
