### ISSUE TITLE
Possible to get rid of email.php?

### ISSUE THREAD

**Issue by mavam** [coolacid/docker-misp#130]
The README says that `email.php` is needed to have in `server-configs`. I tried `docker compose up` without mounting `server-configs` and things still work out fine.

Is it really required or optional? It would be great if we can get rid of it, because it's a volume mounted and populated by MISP itself, which is a pain for strictly version-controlled deployments.

**Comment by chrisinmtown** [comment]
I suppose it all depends on whether you configure your MISP instance to email users when events are changed, published, etc. We do not; we set MISP.disable_emailing to True. I configured the docker instance to start with the default copy of email.php as available from git instead of mounting an external version.

FWIW the only config  file mounted to the server container by docker-compose is `config.php` all the others are the default versions, including email.php as mentioned above.

HTH
