### ISSUE TITLE
Chaging MySQL logins

### ISSUE THREAD

**Issue by derfel1989** [coolacid/docker-misp#158]
How can I change MySQL user and password?

I have been changing on YML file manually on the database conf file and NGINX file as well, but nothing works only the default password.

Setup:
Ubuntu 20.04
  Portainer

Thank you!

**Comment by Ari-R** [comment]
I have essentially the same issue to this. I asked the question on the gitter chat but didnt get a response.

I changed the MYSQL_PASSWORD and MYSQL_ROOT_PASSWORD in docker-compose.yml and it seems to work, but when I also change the password in database.php I get an "internal error" error which does not let me access the dashboard. 

Im trying to stop connections to the database using the default "example" password. Not sure if its even required to update the password variable in the database.php file also? If it is required why is it throwing this error?

Have also read about the password being saved in the volume so have tried using --force-recreate so that it would use a new volume but gives same problem

**Comment by derfel1989** [comment]
The same here.

**Comment by coolacid** [comment]
I'm not entirely sure where the problems exist as I can't reproduce these issues. 

I'd suggest you read the for production bits in the readme for details on running this in a more production format.

**Comment by CyberSecDog** [comment]
If you change the password in the docker-compose.yml file after you have rune it once. You need to delete server-config folder that was create the first time or you get the errors.

**Comment by derfel1989** [comment]
> If you change the password in the docker-compose.yml file after you have rune it once. You need to delete server-config folder that was create the first time or you get the errors.

Thank you for your reply.

What I'm doing is editing the docker-compose.yml file with the configurations that I want and then deploying that. However, I get the issue related to the MySQL account. At which point should I delete the server-config folder in this case? Won't I get errors with that?

Once again thank you for your time.

**Comment by derfel1989** [comment]
> I'm not entirely sure where the problems exist as I can't reproduce these issues.
> 
> I'd suggest you read the for production bits in the readme for details on running this in a more production format.

To reproduce the issue you can just deploy a new instance changing the password for `misp` in the lines below.

[docker-compose.yml](https://github.com/coolacid/docker-misp/blob/master/docker-compose.yml)

> environment:
>       - "MYSQL_USER=misp"
>       - "MYSQL_PASSWORD=`example`"

**Comment by coolacid** [comment]
The goal of the docker compose is to boot strap the configuration the first time. Once it's been created, the startup scripts don't make any new changes. This is for enterprises that use their own configuration files outside of the boot-strap.
