### ISSUE TITLE
Add Let's Encrypt Certificate automation feature using Docker Compose

### ISSUE THREAD

**Issue by s3ich4n** [coolacid/docker-misp#161]
Greetings,

I'd be great if someone want to use Let's Encrypt certificate to produce one's MISP service.
I don't know it is a normal production method using [Let's Encrypt certificate](https://letsencrypt.org/), but I think at least this certificate helps some MISP manager to serve their MISP instance securely. Please feel free to comment your opinions below.

And Does this project have some contributing rules to comply with? Because I want to contribute this feature in this repository.

Thank you!

**Comment by coolacid** [comment]
I'd prefer some documentation to set this up. One problem with this, a lot of people don't want an external entity knowing about their MISP instance. Even accidentally trying to get the cert could expose an internal instance. 

In all reality, one should really be building their own docker-compose, or other deployment system instead of using the default.

**Comment by s3ich4n** [comment]
Huge thanks for your reply and your idea, so now I'm going to write some docs about integrating Let's Encrypt Certificate into one's MISP Instance. 😄 

Is there any rules/conventions about adding documentations on this repository? If it is not permitted, I'm planning to write an article on my blog and share a link on this issue.

**Comment by coolacid** [comment]
Blog is fine, link it here for people to reference. I might also slap it into the project wiki with attribution for posterity if you don't mind.
