### ISSUE TITLE
html2markdown module activation

### ISSUE THREAD

**Issue by thezolin** [coolacid/docker-misp#205]
Hello, 

Where and how can we enable the creation of reports from automatic URL parse (html2markdown module)?
We verify that we do not have this feature enabled in MISP UI.  

https://www.misp-project.org/2020/10/08/Event-Reports.html/

Thank you in advance.

**Comment by coolacid** [comment]
I don't understand this question. Is there a bug or something missing? More details are required.

**Comment by a-piers** [comment]
@thezolin  there are 2 parts involved here in order to use this functionality.
The html2markdown module needs to be enabled in MISP Server Settings -> Plugins -> import. You can do that via for instance the custom-entrypoint.sh script.

The second part is a security setting in MISP. By default MISP does not allow to query any arbitrary URL. To enable this, the setting is located in MISP Settings -> Security -> "Security.rest_client_enable_arbitrary_urls". As this can only be changed via CLI (as also mentioned in the settings), you can use the custom-entrypoint.sh script to enable this.

**Comment by thezolin** [comment]
Hi All, 

Thanks for your help. It's solved by now. 

I will close this topic. 

Br, 

Fernando Thezolin
